services:
  app:
    container_name: vehicleapp
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/
    networks:
      - vehicle-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8001:80"

  db:
    container_name: vehicle_db
    image: mysql:8.0
    # ports:
    #   - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - vehicle-network

  redis:
    container_name: vehicle_redis
    image: redis:7-alpine
    restart: unless-stopped
    # ports:
    #   - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - vehicle-network
    command: redis-server --appendonly yes

volumes:
  db_data:
    driver: local
  redis_data:
    driver: local

networks:
  vehicle-network:
    driver: bridge